# Generated by Django 5.2 on 2025-04-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attacks',
            name='Description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attacks',
            name='ShortDescription',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attacks',
            name='nameOfAttack',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
