# Generated by Django 5.2 on 2025-04-27 10:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0002_attacks_description_attacks_shortdescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attacks',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
