# Generated by Django 5.2 on 2025-04-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0003_attacks_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attacks',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
