# Generated by Django 5.2 on 2025-05-09 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0005_incidents_delete_attacks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidents',
            name='Author',
        ),
        migrations.RemoveField(
            model_name='incidents',
            name='Damage',
        ),
        migrations.RemoveField(
            model_name='incidents',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='incidents',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='incidents',
            name='Source',
        ),
    ]
