# Generated by Django 5.2 on 2025-05-09 06:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0006_remove_incidents_author_remove_incidents_damage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incidents',
            name='Author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidents',
            name='Damage',
            field=models.TextField(default="Tupichok"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidents',
            name='Date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidents',
            name='Description',
            field=models.TextField(default="Tupichok"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidents',
            name='Source',
            field=models.TextField(default="Tupichok"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidents',
            name='Status',
            field=models.TextField(default="Tupichok"),
            preserve_default=False,
        ),
    ]
