# Generated by Django 5.2 on 2025-05-09 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0007_incidents_author_incidents_damage_incidents_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidents',
            old_name='Damage',
            new_name='Attack',
        ),
    ]
